/// @description
if(obj_suq.vambraceK) { o1 = false; o2 = false; }
if(instance_exists(o_eFire)) { o1 = false; }
if(obj_suq.vambrace and !obj_suq.vambraceK) { o2 = true; }
if(!o1 and !check)
{
	check = true;
	var _n = instance_create_layer(825,412,"Instances_Action",obj_ninja);
	_n.drop_gun = true;
	_n.bigX = true;
	var _n1 = instance_create_layer(922,765,"Instances_Action",obj_ninja);
	_n1.drop_gun = true;
	_n1.bigX = true;
	var _n2 = instance_create_layer(1097,733,"Instances_Action",obj_ninja);
	_n2.drop_gun = true;
	_n2.bigX = true;
	var _n3 = instance_create_layer(1181,412,"Instances_Action",obj_ninja);
	_n3.drop_gun = true;
	_n3.bigX = true;
	var _n4 = instance_create_layer(1592,412,"Instances_Action",obj_ninja);
	_n4.drop_gun = true;
	_n4.bigX = true;
	var _n5 = instance_create_layer(1592,690,"Instances_Action",obj_ninja);
	_n5.drop_gun = true;
	_n5.bigX = true;
	var _n6 = instance_create_layer(1269,681,"Instances_Action",obj_ninja);
	_n6.drop_gun = true;
	_n6.bigX = true;
	var _n7 = instance_create_layer(1404,806,"Instances_Action",obj_ninja);
	_n7.drop_gun = true;
	_n7.bigX = true;
	var _n8 = instance_create_layer(1704,769,"Instances_Action",obj_ninja);
	_n8.drop_gun = true;
	_n8.bigX = true;
	var _n9 = instance_create_layer(1693,507,"Instances_Action",obj_ninja);
	_n9.drop_gun = true;
	_n9.bigX = true;
	var _n10 = instance_create_layer(1401,1109,"Instances_Action",obj_ninja);
	_n10.drop_gun = true;
	_n10.bigX = true;
	var _n11 = instance_create_layer(1290,882,"Instances_Action",obj_ninja);
	_n11.drop_gun = true;
	_n11.bigX = true;
	var _n12 = instance_create_layer(1198,989,"Instances_Action",obj_ninja);
	_n12.drop_gun = true;
	_n12.bigX = true;
	var _n13 = instance_create_layer(1204,1192,"Instances_Action",obj_ninja);
	_n13.drop_gun = true;
	_n13.bigX = true;
	var _n14 = instance_create_layer(953,1179,"Instances_Action",obj_ninja);
	_n14.drop_gun = true;
	_n14.bigX = true;
	var _n15 = instance_create_layer(705,579,"Instances_Action",obj_ninja);
	_n15.drop_gun = true;
	_n15.bigX = true;
	var _n16 = instance_create_layer(532,646,"Instances_Action",obj_ninja);
	_n16.drop_gun = true;
	_n16.bigX = true;
	var _n17 = instance_create_layer(698,411,"Instances_Action",obj_ninja);
	_n17.drop_gun = true;
	_n17.bigX = true;
	var _n18 = instance_create_layer(814,856,"Instances_Action",obj_ninja);
	_n18.drop_gun = true;
	_n18.bigX = true;
	var _n19 = instance_create_layer(610,1006,"Instances_Action",obj_ninja);
	_n19.drop_gun = true;
	_n19.bigX = true;
	var _n20 = instance_create_layer(478,771,"Instances_Action",obj_ninja);
	_n20.drop_gun = true;
	_n20.bigX = true;
}