audio_play_sound(snd_fire,3,false,.7*o_saveload.sfxvol);
instance_create(x,y,obj_fireSH);
instance_create(x,y,obj_fireSH);
instance_create(x,y,obj_fireSH);
instance_create(x,y,obj_fireSH);
instance_create(x,y,obj_fireSH);
instance_create(x,y,obj_fireSH);
instance_create(x,y,obj_fireSH);
instance_create(x,y,obj_fireSH);
instance_create(x,y,obj_fireSH);
instance_create(x,y,obj_fireSH);
instance_create(x,y,obj_fireSH);
instance_create(x,y,obj_fireSH);
instance_create(x,y,obj_fireSH);
instance_create(x,y,obj_fireSH);
instance_create(x,y,obj_fireSH);
instance_create(x,y,obj_fireSH);
instance_create(x,y,obj_fireSH);
instance_create(x,y,obj_fireSH);
instance_create(x,y,obj_fireSH);
instance_create(x,y,obj_fireSH);
instance_create(x,y,obj_fireSH);
instance_create(x,y,obj_fireSH);
instance_create(x,y,obj_fireSH);
instance_create(x,y,obj_fireSH);
instance_create(x,y,obj_fireSH);
instance_create(x,y,obj_fireSH);
instance_create(x,y,obj_fireSH);
instance_create(x,y,obj_fireSH);
instance_create(x,y,obj_fireSH);
instance_create(x,y,obj_fireSH);
instance_create(x,y,obj_fireSH);
health = 100;
obj_suq.image_alpha = 1;
obj_suq.lv -= 5;
obj_suq.lv = floor(obj_suq.lv);