switch(room)
{
	case r_trap0: if(sCheck2) then { audio_play_sound(snd_l1,12,false,o_saveload.sfxvol); sCheck2 = false; } if(instance_number(obj_zombie) == 0 and sCheck) then { audio_play_sound(snd_lvl1,1,false,o_saveload.sfxvol); sCheck = false; alarm_set(0,300); } break;
	case r_trap1: if(sCheck2) then { audio_play_sound(snd_l2,12,false,o_saveload.sfxvol); sCheck2 = false; }  if((instance_number(obj_zombieEx)+instance_number(obj_zombieF)) == 0 and sCheck) then { audio_play_sound(snd_lvl1,1,false,o_saveload.sfxvol); sCheck = false; alarm_set(1,300); } break;
	case r_trap2: if(sCheck2) then { audio_play_sound(snd_l3,12,false,o_saveload.sfxvol); sCheck2 = false; }  if((instance_number(obj_turret)+instance_number(obj_MTurret)+instance_number(obj_HTurret)) == 0 and sCheck) then { audio_play_sound(snd_lvl1,1,false,o_saveload.sfxvol); sCheck = false; alarm_set(2,300); } break;
	case r_trap3: if(sCheck2) then { audio_play_sound(snd_l4,12,false,o_saveload.sfxvol); sCheck2 = false; }  if((instance_number(obj_spinBlades)+instance_number(obj_MTurret)+instance_number(obj_HTurret)) == 0 and sCheck) then { audio_play_sound(snd_lvl1,1,false,o_saveload.sfxvol); sCheck = false; alarm_set(3,300); } break;
	case r_trap4: if(sCheck2) then { audio_play_sound(snd_l5,12,false,o_saveload.sfxvol); sCheck2 = false; }  if((instance_number(obj_hGturret)+instance_number(obj_MGTurret)+instance_number(obj_turretBoss)+instance_number(obj_zombieF)) == 0 and sCheck) then { audio_play_sound(snd_lvl1,1,false,o_saveload.sfxvol); sCheck = false; alarm_set(4,300); } break;
	case r_trap5: if(sCheck2) then { audio_play_sound(snd_l6,12,false,o_saveload.sfxvol); sCheck2 = false; }  if((instance_number(obj_zombie)+instance_number(obj_zombieF)+instance_number(obj_zombieEx)) == 0 and sCheck) then { audio_play_sound(snd_lvl1,1,false,o_saveload.sfxvol); sCheck = false; alarm_set(5,300); } break;
	case r_trap6: if(sCheck2) then { audio_play_sound(snd_l7,12,false,o_saveload.sfxvol); sCheck2 = false; }  if((instance_number(object98)+instance_number(object99)+instance_number(obj_spinBlades)) == 0 and sCheck) then { audio_play_sound(snd_lvl1,1,false,o_saveload.sfxvol); sCheck = false; alarm_set(6,300); } break;
	case r_trap7: if(sCheck2) then { audio_play_sound(snd_l8,12,false,o_saveload.sfxvol); sCheck2 = false; }  if((instance_number(obj_zombieBoss)+instance_number(obj_zombieF)+instance_number(obj_MTurret)) == 0 and sCheck) then { audio_play_sound(snd_l9,1,false,o_saveload.sfxvol); sCheck = false; alarm_set(7,720); } break;
	//case r_trap8: if(instance_number(obj_zombie) == 0 and sCheck) then { audio_play_sound(snd_lvl1,1,false); sCheck = false; alarm_set(8,420); }
	//case r_trap9: if(instance_number(obj_zombie) == 0 and sCheck) then { audio_play_sound(snd_lvl1,1,false); sCheck = false; alarm_set(9,420); }
}